### ISSUE TITLE
TypeError: imagemin.jpegtran is not a function

### ISSUE THREAD

**Issue by seanhudson** [stevepolitodesign/wordpress-bootstrap-starter-theme#1]
After I run `npm start`, I see the following...

```
> your-project@1.0.0 start /home/vagrant/Sites/agent-legend-web-site/public/wp-content/themes/wordpress-bootstrap-starter-theme-master
> gulp

[00:36:37] Requiring external module @babel/register
[00:36:40] Using gulpfile ~/Sites/agent-legend-web-site/public/wp-content/themes/wordpress-bootstrap-starter-theme-master/gulpfile.babel.js
[00:36:40] Starting 'default'...
[00:36:40] Starting 'styles'...
[00:36:40] Starting 'vendorsJS'...
[00:36:40] Starting 'customJS'...
[00:36:40] Starting 'images'...
[00:36:40] Starting 'browsersync'...
[00:36:40] Starting '<anonymous>'...
[00:36:40] 'images' errored after 86 ms
[00:36:40] TypeError: imagemin.jpegtran is not a function
    at /home/vagrant/Sites/agent-legend-web-site/public/wp-content/themes/wordpress-bootstrap-starter-theme-master/gulpfile.babel.js:324:16
    at images (/home/vagrant/Sites/agent-legend-web-site/public/wp-content/themes/wordpress-bootstrap-starter-theme-master/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:419:14)
    at runBound (domain.js:432:12)
    at asyncRunner (/home/vagrant/Sites/agent-legend-web-site/public/wp-content/themes/wordpress-bootstrap-starter-theme-master/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

[00:36:40] 'default' errored after 88 ms
[00:36:40] The following tasks did not complete: styles, vendorsJS, customJS, browsersync, <anonymous>
[00:36:40] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! your-project@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the your-project@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-02-12T00_36_40_798Z-debug.log
```

**Comment by stevepolitodesign** [comment]
What version of `node` are you running?
